### ISSUE TITLE
MSTest V2 backlog

### ISSUE THREAD

**Issue by pvlakshm** [microsoft/testfx#144]
## MSTest V2 backlog
Here is our [roadmap](https://github.com/Microsoft/testfx-docs/blob/master/roadmap.md). It calls out the broad themes for our work. The below list of issues breaks that down to the line item level focus of our work aligned to the roadmap. Please vote on the individual issues below - That would help us prioritize our backlog.

**Extensibility**
- [x] Custom Attributes: [#137](https://github.com/Microsoft/testfx/issues/137)
- [x] Custom Assertions: [#116](https://github.com/Microsoft/testfx/issues/116)
- [x] Data driven testing: [#141](https://github.com/Microsoft/testfx/issues/141) 
- [ ] Custom execution: [#139](https://github.com/Microsoft/testfx/issues/139)
- [ ] Action Attributes: [#140](https://github.com/Microsoft/testfx/issues/140)

**Features**
- [x] Test Inheritance for base classes in different assemblies: [#23](https://github.com/Microsoft/testfx/issues/23)
- [x] Console.Writeline for .NET Core: [#18](https://github.com/Microsoft/testfx/issues/18)
- [x] Ability to provide reason for ignored tests: [#126](]https://github.com/Microsoft/testfx/issues/126)
- [x] Update VB Unit test templates: [#132](https://github.com/Microsoft/testfx/issues/132)
- [x] Design mode awareness to query source information: [#119](https://github.com/Microsoft/testfx/issues/119)
- [x] In-assembly parallel execution: [#142](https://github.com/Microsoft/testfx/issues/142)
- [ ] ClassInitializer inheritance: [#143](https://github.com/Microsoft/testfx/issues/143)
- [x] Timeouts: [#26](https://github.com/Microsoft/testfx/issues/26)

**Documentation**
- [x] Add API documentation: [#153](https://github.com/Microsoft/testfx/issues/153)
- [x] Documentation on Test discovery/Run flow [#155](https://github.com/Microsoft/testfx/issues/155)

**Compat issues**
- [ ] Ordered tests: [#25](https://github.com/Microsoft/testfx/issues/25)

**Comment by AbhitejJohn** [comment]
> Test Inheritance for base classes in different assemblies: #23

This is now fixed and can be enabled when one passes in a runsettings similar to below:
```
<RunSettings>    
  <MSTest> 
    <EnableBaseClassTestMethodsFromOtherAssemblies>true</EnableBaseClassTestMethodsFromOtherAssemblies> 
  </MSTest> 
</RunSettings>
```

**Comment by melleck** [comment]
When can we expect Ordered tests: #25 support to be added in MS Test V2? It has been over a year now. Voting is also closed for this issue. Please update with the Expected time? Need it badly. Thanks.

**Comment by Evangelink** [comment]
Closing this ticket as it is not bringing much value.
