### ISSUE TITLE
Make TestFx repo CPS based

### ISSUE THREAD

**Issue by jayaranigarg** [microsoft/testfx#606]
## CPS backlog
This should address other related issues like -

- [ ] Running build.cmd locally results in failure [#605](https://github.com/Microsoft/testfx/issues/605)
- [ ] [NetCore] Enable support for messages/warnings related to Deployment Items for languages other than English [#591](https://github.com/Microsoft/testfx/issues/591)
- [ ] Consolidate the adapter and framework nuget packages (with framework being the longterm one) [#193](https://github.com/Microsoft/testfx/issues/193)
- [ ] Set DisableAppDomain to true, by default

**Comment by jayaranigarg** [comment]
@cltshivash : Please update this checklist as we uncover/identify more issues that needs to be resolved as part of CPS change.

**Comment by parrainc** [comment]
@jayaranigarg just wondering... will be PR #411 taken into consideration as part of this feature? Or maybe it's out of scope?

**Comment by jayaranigarg** [comment]
@parrainc : We are still working on the design aspect of the CPS change, so mostly PR #411 will not be considered.

**Comment by parrainc** [comment]
Oh, I see. Just wanted to know if still worth it to invest time on #411 but i think is not.
Thanks for the update. I'll be checking at the issues to see if there more things I can help to get the repo CPS :)

**Comment by StingyJack** [comment]
What is a CPS?

**Comment by parrainc** [comment]
@StingyJack late but, CPS stands for: Common Project System ([check here](https://github.com/microsoft/vsprojectsystem))

**Comment by Evangelink** [comment]
I will move forward by closing this ticket because it seems like most issues have already been handled.
